global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['Prometheus:9090']
  - job_name: redis-exporter
    static_configs:
      - targets: ['redis-exporter:9121']
  - job_name: vectro-lite-redis-exporter
    static_configs:
      - targets: ['vectro-lite-redis-exporter:9121']