version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6380:6379
    expose:
      - 6380
    restart: unless-stopped
    networks:
      - redis
      
networks:
  redis:
    driver: bridge
    name: redis